version: '3.4'

services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./.volume_data/postgres:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./backend:/home/app/backend
    command: python manage.py runserver 0.0.0.0:8000
    entrypoint: "bash entrypoint.sh"
    env_file:
      - .env
